# Generated by Django 5.2.12 on 2026-07-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
