# Generated by Django 5.2.12 on 2026-07-20 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_careermap_mockinterview_preparationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=200.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('verbal_score', models.FloatField(default=0.0)),
                ('aptitude_score', models.FloatField(default=0.0)),
                ('coding_easy_score', models.FloatField(default=0.0)),
                ('coding_hard_score', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
